from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from pgvector.sqlalchemy import Vector
from sqlalchemy import Boolean, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.config import get_settings
from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.user import User

_EMBEDDING_DIM = get_settings().embedding_dimensions


class TasteProfile(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """
    A versioned, point-in-time snapshot of a user's reading taste, generated by
    the LLM analysis pipeline (services/ai/taste_profile.py) from their library,
    ratings, reviews, and activity history.

    Profiles are immutable once created — "evolving over time" means we append
    new versions as the user reads more, which lets us show drift over time and
    always recommend against the latest snapshot (`is_current=True`).
    """

    __tablename__ = "taste_profiles"
    __table_args__ = (
        UniqueConstraint("user_id", "version", name="uq_taste_profile_user_version"),
    )

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    is_current: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False, index=True)

    # Human-readable narrative summary, produced via structured LLM output
    # (schemas/taste_profile.py:TasteProfileAnalysis).
    summary: Mapped[str] = mapped_column(Text, nullable=False)

    # Structured analysis: favorite genres/themes/authors, pacing & tone preferences,
    # rating tendencies, notable shifts since the previous version, etc.
    analysis: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # Embedding of the summary, used to find manga whose embeddings are nearby
    # (services/ai/recommendations.py) — i.e. "what matches this user's taste".
    embedding: Mapped[list[float] | None] = mapped_column(Vector(_EMBEDDING_DIM), nullable=True)
    embedding_model: Mapped[str | None] = mapped_column(String(120), nullable=True)

    # Inputs that produced this snapshot, for auditability/reproducibility.
    source_stats: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    user: Mapped["User"] = relationship(back_populates="taste_profiles")

    def __repr__(self) -> str:  # pragma: no cover - debug helper
        return f"<TasteProfile user_id={self.user_id} version={self.version} current={self.is_current}>"
